n=int(input('Digite um numero: '))
print(type(n))
m=float(input('Digite um numero com ponto ex: 5.32 : '))
print(type(m))
o=bool(input('Digite verdadeiro ou falso f/v: '))
print(type(o))
p=bool(input('Digite algo: '))
print(type(p))
q=str(input('Digite uma palavra: '))
print(type(q))